# Generated by Django 5.2.17 on 2026-08-11 01:08

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rag", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "law_id",
                    models.CharField(max_length=50, unique=True, verbose_name="법령ID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="법령명")),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="소관부처"
                    ),
                ),
                (
                    "promulgation_date",
                    models.DateField(blank=True, null=True, verbose_name="공포일자"),
                ),
                (
                    "enforcement_date",
                    models.DateField(blank=True, null=True, verbose_name="시행일자"),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="출처")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LawChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_no",
                    models.CharField(blank=True, max_length=20, verbose_name="조번호"),
                ),
                (
                    "article_title",
                    models.CharField(blank=True, max_length=255, verbose_name="조제목"),
                ),
                ("content", models.TextField(verbose_name="본문")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬순서"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "law",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="rag.law",
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="lawchunk_emb_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
