# Generated by Django 5.2.17 on 2026-08-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="회사명")),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("healthcare", "헬스케어/의료"),
                            ("fintech", "핀테크/금융"),
                            ("ecommerce", "이커머스/쇼핑"),
                            ("edutech", "교육"),
                            ("saas", "일반 SaaS/IT서비스"),
                            ("etc", "기타"),
                        ],
                        max_length=20,
                        verbose_name="업종",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("b2c", "개인 대상(B2C)"),
                            ("b2b", "기업 대상(B2B)"),
                            ("both", "둘 다"),
                        ],
                        max_length=10,
                        verbose_name="사업 형태",
                    ),
                ),
                (
                    "employee_count",
                    models.PositiveIntegerField(default=0, verbose_name="직원 수"),
                ),
                (
                    "handles_personal_data",
                    models.BooleanField(default=True, verbose_name="개인정보 취급"),
                ),
                (
                    "handles_sensitive_data",
                    models.BooleanField(
                        default=False, verbose_name="민감정보(건강 등) 취급"
                    ),
                ),
                (
                    "handles_location_data",
                    models.BooleanField(default=False, verbose_name="위치정보 취급"),
                ),
                (
                    "handles_financial_data",
                    models.BooleanField(
                        default=False, verbose_name="신용/결제정보 취급"
                    ),
                ),
                (
                    "handles_minor_data",
                    models.BooleanField(
                        default=False, verbose_name="만 14세 미만 정보 취급"
                    ),
                ),
                (
                    "does_online_sales",
                    models.BooleanField(default=False, verbose_name="온라인 판매"),
                ),
                (
                    "does_marketing",
                    models.BooleanField(
                        default=False, verbose_name="광고성 정보 전송(이메일/문자)"
                    ),
                ),
                (
                    "overseas_transfer",
                    models.BooleanField(
                        default=False, verbose_name="개인정보 국외 이전"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
