# Generated by Django 5.2.17 on 2026-08-12 02:33

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="문서명")),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="출처/발행처"
                    ),
                ),
                (
                    "total_pages",
                    models.PositiveIntegerField(default=0, verbose_name="총 페이지"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter",
                    models.CharField(blank=True, max_length=150, verbose_name="장"),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="절/항 제목"
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="페이지"
                    ),
                ),
                ("content", models.TextField(verbose_name="본문")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬순서"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="work.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="docchunk_emb_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
